V_HOSTNAME=wcs-vagrant
V_IP_ADDRESS=192.168.168.150
V_UNIXUSER=oracle
V_UNIXGROUP=oracle
V_UNIXUSERHOME=/home/oracle

V_KITS_DIRECTORY=../kits

V_PORT=9191
V_SITES_INSTALLDIR=/u00/sites
V_SITES_SHAREDDIR=/u00/Shared
V_TOMCAT_INSTALLDIR=/u00/tomcat
V_JDK_INSTALLDIR=/u00/jdk
V_SITES_PATCHLEVEL=patch11

#VAGRANT_LOG=info
VAGRANT_LOGFILE=vagrant.log

V_VAGRANT_SSHPORT=2222
V_VAGRANT_MEMORY=1024
V_VAGRANT_GUI=false

